### ISSUE TITLE
refit & painting function

### ISSUE THREAD

**Issue by 3rdmates** [Yozora3/JPplusPrivate#25]
Good day sir,

I found some issue after updating grf to 0.4.7 ver.

Almost of car's refit & painting function is gone, so all of new car's painting is too variable to unify the car's painting.

does it have an error? or normal update?

![tobu 70000](https://github.com/Yozora3/JPplusPrivate/assets/102298742/bd0235da-b5b0-4a42-be3a-049c15abfe4a)

For example, Tobu 70000//70090 car has 3 paintings, but now, only default painting is available, other paintings can't be chosen.

**Comment by Yozora3** [comment]
Yes this is a bug introduced due to me trying to fix another bug. Thank you for pointing this out, as I thought the scale of the problem wasn't this big

**Comment by Yozora3** [comment]
Fixed, will be included in the next update
