### ISSUE TITLE
propose about customizing car's speed and capacity

### ISSUE THREAD

**Issue by 3rdmates** [Yozora3/JPplusPrivate#4]
Could you adjust the transport volume to be similar to the JP+ train set? I think the current JP+ metro set's passenger capacity is not enough to carry lot of population, so it doesn't reflecting the rush hour.

_And, I hope this newgrf's trains could run at another newgrf's rail. Because, japan track is to complex to running..._ It can be run if japan track wasn't applied.

In addition, I would like to propose an additional function that can change each speed. I think this is also a function that can broaden users' choices. happy new year. and please write the donation account. if I have enough money, I will donate to your team for more better newgrf. Thx to read it :)

**Comment by Yozora3** [comment]
Sure thing, I will add more parameters to select capacity, as well as more railtypes to the set.
Could you please be more specific, what do you mean by changing speed? Is it max/service speed or adding +10/+20/etc km/h by a parameter?
Thank you for a donation proposition. I've added the info on the project page. Please be aware that JP+ team doesn't have one "unified" account, so to support everyone you should contact every member separately.
Happy holidays!

**Comment by 3rdmates** [comment]
Thx for reading my comments. :)
Speed Change means we vary trains' speed by parameters. Maybe you can refer JPplusSet's parameters. Because I before proposed controlling capacity and speed by parameters to them. -_- 
So it was applied!

And I have another request. 
I don't use Japanese Rail Set, but these trains works very well and can buy easily. But newgrf's error message is still annoying me. Can I ask you to fix about this problem?

**Comment by Yozora3** [comment]
I've changed the error to a warning, that suggests using JapanSet Tracks in newGrf menu, without any error messages ingame. This fix will be included in the next update. 
I don't see any JPplus speed parameters tho, only capacity. As far as I understood you meant "boosting" speed by some amount.
Btw, you can change metros' capacity already in settings. But still, I'll eventually add more than "high" and "very high" capacity modifiers

**Comment by 3rdmates** [comment]
Thx for answering my comments, ;)

**Comment by 3rdmates** [comment]
I suggest another improvements in the next update. Now, the passengers car is divided by the gauge of rail. - 3rd rail, narrow and 1372/standard gauge.
I think it is needed to integrate or name each cars gauge scale.

**Comment by Yozora3** [comment]
Unfortunately game does not allow multigauge wagons, so it's impossible to unify all of them into one. I'll add gauges to the names of each wagon.

**Comment by 3rdmates** [comment]
I suggest another improvements.What do you think about inserting eidan icon to the cars they made in eidan? I'm sorry to suggest too much.

**Comment by Yozora3** [comment]
Purchase menu already has 2 icons of company and line, so the third one would be a mess.

**Comment by 3rdmates** [comment]
I think eidan 1000 series' name is needed to change to Tokyo metro 1000 series. It may be confused.

**Comment by 3rdmates** [comment]
Thx for reflecting my ideas.

But I'm sorry to tell about capacity.

If you modify train's capacity, I think all cars need to be modified. Not only wagon, Engine cars(e.g. 1000 series) need to be modified.

I think it'll be good to refer to it when you work on it.

**Comment by Yozora3** [comment]
Capacities are modified by the parameter already.
The engine car has less capacity just like in real world (driver cab takes car's space)

![image](https://user-images.githubusercontent.com/96115762/213859651-640e653c-a2e5-423c-bd41-1906828ecf9d.png)

**Comment by 3rdmates** [comment]
Then, how do you think about customizing trains' capacity?

Customized engine's capacities = Engine car's basic capacities × (parameters ×100%) 
Customized wagon's capacities = Customized engine's capacities × (105 to 110%)

I'm sorry to keep asking for complicated work.

But, metro grf's the highest capacity is not enough to carry many passengers.

![1674323409276](https://user-images.githubusercontent.com/102298742/213880233-f2cb09a8-8c0d-4610-93b0-00133cf2e856.png)
![1674323408100](https://user-images.githubusercontent.com/102298742/213880234-c73bd1d9-6eaa-43c0-a5a2-153a0f7cfe28.png)

First car is jp+ set's E235 series yamanote livery.
Others are Tokyo metro's third rail cars.

**Comment by Yozora3** [comment]
First of all these trains are different classes. E235 is 20m long and has 4 doors, 1000/2000 series are 18m long and have 3 doors. They can't have same capacity. 
More of that, 450 commuters is impossible in real life. It would mean roughly 9 people per m^2, standing not only on floor, but on seats as well.
Still, I did custom capacity and reworked capacity parameter system, so you can do even such things.

**Comment by 3rdmates** [comment]
I have a tendency to implement rush hour, so I set a congestion level of 250% as the upper limit of the capacity. So, although the purpose of pursuing is different from yours, I liked the design of the jp+ set very much, so I often expressed my opinion on the capacity. I'm sorry to bother you.

**Comment by 3rdmates** [comment]
I downloaded updated version. Thanks too much.

P.s. Is train composition changed? Engine car is only one.

**Comment by Yozora3** [comment]
What do you mean by composition?

**Comment by 3rdmates** [comment]
before the metro car's composition was:
engine - wagon - wagon - (wagons) - wagon - wagon - engine

but today I changed the car, latest version's composition is:
engine - wagon - wagon - (wagons) - wagon - wagon

the engine car's length was shorten 1.0 to 0.5

**Comment by Yozora3** [comment]
It always was one engine per train. There should be error if you will try to attach one more engine to the end or center.

**Comment by 3rdmates** [comment]
Oh, I confused with JP+ set.

Anyway, thanks a lot. I will use your grf a lot in my map for metro car. :)

**Comment by 3rdmates** [comment]
Can I ask something to you? I know you don't develop JP multiple set. But if you can contact to JP multiple set's dev. team, I want to suggest about changing multiple set's capacity like metro set's capacity.

Multiple set's option varies 'only' wagon's capacity. So, It looks very unbalanced. If you can contact, plz ask to change multiple set's capacity like your metro set. Customize engine car's capacity, and then plus some percents to wagon.

**Comment by 3rdmates** [comment]
Some Tobu cars' capacity is two times larger than other car in customized capacity option. Can you check?

**Comment by Yozora3** [comment]
Could you please be more specific, which trains have this issue? 
For rapid express capacity will always be lower, as they have lower cargo decay rate, imitating "reserved" seat.

**Comment by Yozora3** [comment]
Ok, should be fixed now
